promise
    .then(f1)
    .catch(f2);
// Короткий ответ: нет, они не эквивалентны: